### ISSUE TITLE
ioc_fanger.defang('8.8.8.8') == '8[.]8.8[.]8' instead of '8[.]8[.]8[.]8'

### ISSUE THREAD

**Issue by rooterkyberian** [ioc-fang/ioc_fanger#3]
* IOC Fanger version: v1.0.0
* Python version: 3.6.4

### Description

```python
ioc_fanger.defang('8.8.8.8') == '8[.]8.8[.]8'
ioc_fanger.defang('a.b.c') == 'a[.]b.c'
```

The fact the middle dot was not escaped took me by surprise and seem like a bug or is there an explanation for this?

Seems to me like every other defanger just replaces every `.` with `[.]`, so I would expect `ioc_fanger.defang`do the same.

**Comment by fhightower** [comment]
Good question. The reason IP addresses are defanged in this way is due to the regex I'm using for the defanging process: `\\S(\\.)\\S` (available here: https://github.com/ioc-fang/datasets/blob/master/defang.json#L3).

Rather than defanging all `.` characters, I'm only defanging `.` characters that are surrounded by non-whitespace characters. This means that, given `1.2.3.4` as input, the defanger will match and replace `1.2` and will then process the remainder of the IP address (in this case `.3.4`). Thus, the middle dot doesn't get replaced. I'm going to close the issue for now, but let me know if there is a compelling reason I've overlooked to change how the defanging works.
